client_config_backend: settings
client_config:
	client_id: 339001749505-hkusht54smajquaootnpqjfgaiqv4pfr.apps.googleusercontent.com
	client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials_module.json

get_refresh_token: True

oauth_scope:
	- https://www.googleapis.com/auth/drive